# fly.toml app configuration file generated for yayindenizi-backend on 2026-03-14T20:56:57+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yayindenizi-backend'
primary_region = 'fra'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
